version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - auto_test11_DB__uri=postgresql://postgres:postgres@db:5432/auto_test11
      - auto_test11_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: auto_test11_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/auto_test11_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=auto_test11, auto_test11_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
